apiVersion: v1
kind: ConfigMap
metadata:
  name: rx-demo-config
data:
  OTEL_ENVIRONMENT: "tanzu"
  LOKI_ENDPOINT: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  TEMPO_ENDPOINT: "http://tempo.monitoring.svc.cluster.local:4318"
