apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-sync-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-model-projection
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rx-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: loadgen
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-registry
