apiVersion: v1
kind: ConfigMap
metadata:
  name: rx-demo-config
data:
  LOKI_ENDPOINT: "http://loki.rx-observability.svc.cluster.local:3100/loki/api/v1/push"
  TEMPO_ENDPOINT: "http://tempo.rx-observability.svc.cluster.local:4318"
  OTEL_ENVIRONMENT: "k3s-demo"
