apiVersion: v1
kind: ConfigMap
metadata:
  name: rx-demo-config
data:
  OTEL_ENDPOINT_HTTP: "http://otel-collector.rx-demo.svc.cluster.local:4318"
  OTEL_SERVICE_NAMESPACE: "rx"
  OTEL_ENVIRONMENT: "lab"
  LOKI_ENDPOINT: "http://loki.monitoring.local:3100/loki/api/v1/push"
  TEMPO_ENDPOINT: "http://tempo.monitoring.local:4318"
  RABBITMQ_HOST: "rabbitmq"
  REDIS_ENDPOINT: "redis:6379"
  API_BASE_URL: "http://api-gateway.rx-demo.svc.cluster.local:8080"
