apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rx-demo
resources:
  - namespace.yaml
  - config.yaml
  - otel-collector.yaml
  - rabbitmq.yaml
  - redis.yaml
  - mssql.yaml
  - apps.yaml
  - loadgen-job.yaml
commonLabels:
  app.kubernetes.io/part-of: rx-demo
