apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    app.kubernetes.io/name: mssql
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mssql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rx-demo-secrets
                  key: SA_PASSWORD
          ports:
            - name: sql
              containerPort: 1433
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app.kubernetes.io/name: mssql
spec:
  selector:
    app.kubernetes.io/name: mssql
  ports:
    - name: sql
      port: 1433
      targetPort: sql
