apiVersion: v1
kind: Secret
metadata:
  name: rx-demo-secrets
type: Opaque
stringData:
  SA_PASSWORD: "<set-locally>"
  RABBITMQ_DEFAULT_USER: "<set-locally>"
  RABBITMQ_DEFAULT_PASS: "<set-locally>"
